# Generated by Django 3.0.8 on 2020-07-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0002_auto_20200706_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
