# Generated by Django 3.2 on 2021-04-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0018_auto_20210428_1349'),
    ]
