# Generated by Django 3.2 on 2021-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0020_remove_categories_type'),
    ]