# Generated by Django 3.2 on 2021-04-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0021_auto_20210428_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
