# Generated by Django 3.2 on 2021-04-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0023_foodtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
