# Generated by Django 3.2 on 2021-04-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0025_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='food_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='foodtaskerapp.foodtype'),
        ),
    ]
