# Generated by Django 3.2 on 2021-04-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0026_meal_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='food_type', to='foodtaskerapp.foodtype'),
        ),
    ]
